### PR TITLE
Adds motion control

### PR DESCRIPTION
**Pull request by xdghcnt**

### CODE REVIEW

**Comment by filidorwiese** [comment]
Thanks for your contribution! Very cool idea to add device motion sensors. I did find it a lot harder to steer the meteor. Not sure I would want to enable this by default. And it would need an icon for in stead of the text "enabled sensors" somewhere to toggle sensors. Could you amend that?

Btw, just getting Multeor working again on my machine was a challenge, I would do stuff so much differently now. Maybe one day I will find some time to rewrite the way it runs and build (using npm, docker, webpack and getting rid of java andruby)

**Comment by xdghcnt** [comment]
I'm agree it could be harder to controll with it, but I think there should be that option for demostration purposes at least ^_^
Icon like this? Sure, I'll add it
ss 2018-07-13 at 06 45 07
(Btw, I'm not even tried to run project, heh, tested it only in client with Chrome DevTools by remote debug)

**Comment by filidorwiese** [comment]
Yes that icon looks nice! Could it be a bit smaller and have an active/inactive state (for example color change, opacity, or something like that)? If you'd add it I'll merge the PR. Thanks again ;)

**Comment by xdghcnt** [comment]
Done~
ss 2018-07-17 at 06 18 51

**Comment by filidorwiese** [comment]
Thanks it's looking sharp!

**Comment by filidorwiese** [comment]
I've updated multeor.com to include your motion control logic!

**Pull request merged**
